In [253]:
import numpy as np
import pandas as pd
import ast
from sklearn.feature_extraction.text import CountVectorizer
import nltk
import pickle

In [254]:
movies=pd.read_csv('tmdb_5000_movies.csv')
credits=pd.read_csv('tmdb_5000_credits.csv')

In [255]:
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",10-12-2009,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800

In [256]:
credits.head(1)

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [257]:
movies = movies.merge(credits,on='title')

In [258]:
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [259]:
movies=movies[['id','title','overview','genres','keywords','cast','crew']]

In [260]:
movies.head(1)

,id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [261]:
movies.isnull().sum()

id          0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [262]:
movies.dropna(inplace=True)

In [263]:
movies.duplicated().sum()

0

In [264]:
movies.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [265]:
def convert(obj):
    l = []
    for i in ast.literal_eval(obj): #literal_eval funtions is mainlly convert string to list
            l.append(i['name'])
    return l

In [266]:
movies['genres']=movies['genres'].apply(convert) #used to apply a function along an axis of the DataFrame

In [267]:
movies.head()

,id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...,"[Action, Adventure, Crime]","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [268]:
movies['keywords']=movies['keywords'].apply(convert)

In [269]:
movies.head()

,id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [270]:
def convert3(obj):
    l=[]
    count = 0
    for i in ast.literal_eval(obj):
        if count != 3:
            l.append(i['name'])
            count +=1
        else:
            break
    return l

In [271]:
movies['cast'] = movies['cast'].apply(convert3)

In [272]:
movies.head()

,id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, LÃ©a Seydoux]","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [273]:
def fetch_director(obj):
    l=[]
    for i in ast.literal_eval(obj):
        if i['job']=='Director':
            l.append(i['name'])
            break
    return l

In [274]:
movies['crew']=movies['crew'].apply(fetch_director)

In [284]:
movies.head()

,id,title,overview,genres,keywords,cast,crew,id1
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron],19995
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski],285
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, LÃ©a Seydoux]",[Sam Mendes],206647
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan],49026
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton],49529

In [291]:
movies["overview1"] = movies["overview"]

In [292]:
movies

,id,title,overview,genres,keywords,cast,crew,overview1
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron],"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski],"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, LÃ©a Seydoux]",[Sam Mendes],A cryptic message from Bondâ€™s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan],Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton],"John Carter is a war-weary, former military ca..."
...,...,...,...,...,...,...,...,...
4803,9367,El Mariachi,El Mariachi just wants to play his guitar and ...,"[Action, Crime, Thriller]","[united statesâ€“mexico barrier, legs, arms, pap...","[Carlos Gallardo, Jaime de Hoyos, Peter Marqua...",[Robert Rodriguez],El Mariachi just wants to play his guitar and ...
4804,72766,Newlyweds,A newlywed couple's honeymoon is upended by th...,"[Comedy, Romance]",[],"[Edward Burns, Kerry BishÃ©, Marsha Dietlein]",[Edward Burns],A newlywed couple's honeymoon is upended by th...
4805,231617,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...","[Comedy, Drama, Romance, TV Movie]","[date, love at first sight, narration, investi...","[Eric Mabius, Kristin Booth, Crystal Lowe]",[Scott Smith],"""Signed, Sealed, Delivered"" introduces a dedic..."
4806,126186,Shanghai Calling,When ambitious New York attorney Sam is sent t...,[],[],"[Daniel Henney, Eliza Coupe, Bill Paxton]",[Daniel Hsia],When ambitious New York attorney Sam is sent t...
4807,25975,My Date with Drew,Ever since the second grade when he first saw ...,[Documentary],"[obsession, camcorder, crush, dream girl]","[Drew Barrymore, Brian Herzlinger, Corey Feldman]",[Brian Herzlinger],Ever since the second grade when he first saw ...

In [294]:
movies['overview']=movies['overview'].apply(lambda x:x.split())

In [295]:
movies['genres']=movies['genres'].apply(lambda x:[i.replace(" ","")for i in x])
movies['keywords']=movies['keywords'].apply(lambda x:[i.replace(" ","")for i in x])
movies['cast']=movies['cast'].apply(lambda x:[i.replace(" ","")for i in x])
movies['crew']=movies['crew'].apply(lambda x:[i.replace(" ","")for i in x])

In [296]:
movies.head()

,id,title,overview,genres,keywords,cast,crew,overview1
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski],"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LÃ©aSeydoux]",[SamMendes],A cryptic message from Bondâ€™s past sends him o...
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan],Following the death of District Attorney Harve...
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton],"John Carter is a war-weary, former military ca..."

In [297]:
movies['tags']= movies['overview'] + movies['genres'] + movies['keywords'] +movies['cast'] + movies['crew']

In [298]:
movies.head()

,id,title,overview,genres,keywords,cast,crew,overview1,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],"In the 22nd century, a paraplegic Marine is di...","[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski],"Captain Barbossa, long believed to be dead, ha...","[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LÃ©aSeydoux]",[SamMendes],A cryptic message from Bondâ€™s past sends him o...,"[A, cryptic, message, from, Bondâ€™s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan],Following the death of District Attorney Harve...,"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton],"John Carter is a war-weary, former military ca...","[John, Carter, is, a, war-weary,, former, mili..."

In [300]:
new_df = movies[['id','title','tags','overview','genres','cast','crew','overview1']]

In [301]:
new_df

,id,title,tags,overview,genres,cast,crew,overview1
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski],"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send...","[A, cryptic, message, from, Bondâ€™s, past, send...","[Action, Adventure, Crime]","[DanielCraig, ChristophWaltz, LÃ©aSeydoux]",[SamMendes],A cryptic message from Bondâ€™s past sends him o...
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan],Following the death of District Attorney Harve...
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton],"John Carter is a war-weary, former military ca..."
...,...,...,...,...,...,...,...,...
4803,9367,El Mariachi,"[El, Mariachi, just, wants, to, play, his, gui...","[El, Mariachi, just, wants, to, play, his, gui...","[Action, Crime, Thriller]","[CarlosGallardo, JaimedeHoyos, PeterMarquardt]",[RobertRodriguez],El Mariachi just wants to play his guitar and ...
4804,72766,Newlyweds,"[A, newlywed, couple's, honeymoon, is, upended...","[A, newlywed, couple's, honeymoon, is, upended...","[Comedy, Romance]","[EdwardBurns, KerryBishÃ©, MarshaDietlein]",[EdwardBurns],A newlywed couple's honeymoon is upended by th...
4805,231617,"Signed, Sealed, Delivered","[""Signed,, Sealed,, Delivered"", introduces, a,...","[""Signed,, Sealed,, Delivered"", introduces, a,...","[Comedy, Drama, Romance, TVMovie]","[EricMabius, KristinBooth, CrystalLowe]",[ScottSmith],"""Signed, Sealed, Delivered"" introduces a dedic..."
4806,126186,Shanghai Calling,"[When, ambitious, New, York, attorney, Sam, is...","[When, ambitious, New, York, attorney, Sam, is...",[],"[DanielHenney, ElizaCoupe, BillPaxton]",[DanielHsia],When ambitious New York attorney Sam is sent t...
4807,25975,My Date with Drew,"[Ever, since, the, second, grade, when, he, fi...","[Ever, since, the, second, grade, when, he, fi...",[Documentary],"[DrewBarrymore, BrianHerzlinger, CoreyFeldman]",[BrianHerzlinger],Ever since the second grade when he first saw ...

In [302]:
new_df['tags']=new_df['tags'].apply(lambda x:" ".join(x))

C:\Users\91906\AppData\Local\Temp\ipykernel_14376\487797088.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(lambda x:" ".join(x))

In [303]:
new_df

,id,title,tags,overview,genres,cast,crew,overview1
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski],"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...,"[A, cryptic, message, from, Bondâ€™s, past, send...","[Action, Adventure, Crime]","[DanielCraig, ChristophWaltz, LÃ©aSeydoux]",[SamMendes],A cryptic message from Bondâ€™s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan],Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton],"John Carter is a war-weary, former military ca..."
...,...,...,...,...,...,...,...,...
4803,9367,El Mariachi,El Mariachi just wants to play his guitar and ...,"[El, Mariachi, just, wants, to, play, his, gui...","[Action, Crime, Thriller]","[CarlosGallardo, JaimedeHoyos, PeterMarquardt]",[RobertRodriguez],El Mariachi just wants to play his guitar and ...
4804,72766,Newlyweds,A newlywed couple's honeymoon is upended by th...,"[A, newlywed, couple's, honeymoon, is, upended...","[Comedy, Romance]","[EdwardBurns, KerryBishÃ©, MarshaDietlein]",[EdwardBurns],A newlywed couple's honeymoon is upended by th...
4805,231617,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...","[""Signed,, Sealed,, Delivered"", introduces, a,...","[Comedy, Drama, Romance, TVMovie]","[EricMabius, KristinBooth, CrystalLowe]",[ScottSmith],"""Signed, Sealed, Delivered"" introduces a dedic..."
4806,126186,Shanghai Calling,When ambitious New York attorney Sam is sent t...,"[When, ambitious, New, York, attorney, Sam, is...",[],"[DanielHenney, ElizaCoupe, BillPaxton]",[DanielHsia],When ambitious New York attorney Sam is sent t...
4807,25975,My Date with Drew,Ever since the second grade when he first saw ...,"[Ever, since, the, second, grade, when, he, fi...",[Documentary],"[DrewBarrymore, BrianHerzlinger, CoreyFeldman]",[BrianHerzlinger],Ever since the second grade when he first saw ...

In [304]:
new_df.head()

,id,title,tags,overview,genres,cast,crew,overview1
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski],"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...,"[A, cryptic, message, from, Bondâ€™s, past, send...","[Action, Adventure, Crime]","[DanielCraig, ChristophWaltz, LÃ©aSeydoux]",[SamMendes],A cryptic message from Bondâ€™s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan],Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton],"John Carter is a war-weary, former military ca..."

In [305]:
from nltk.stem.porter import PorterStemmer #Stemming is a technique used to reduce an inflected word down to its word stem/root form
ps=PorterStemmer()

In [306]:
def stem(text):
    y=[]
    for i in text.split():
        y.append(ps.stem(i))
    return " ".join(y)

In [307]:
new_df['tags']=new_df['tags'].apply(stem)

C:\Users\91906\AppData\Local\Temp\ipykernel_14376\3514595201.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(stem)

In [308]:
cv = CountVectorizer(max_features=5000,stop_words='english')

In [309]:
vectors = cv.fit_transform(new_df['tags']).toarray()

In [310]:
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [311]:
from sklearn.metrics.pairwise import cosine_similarity    #method to calculate cosine similarity #measure distance between two vectors

In [312]:
similarity = cosine_similarity(vectors)

In [313]:
def recommend(movie):
    movie_index=new_df[new_df['title'] ==  movie].index[0] #finding the index of the movie
    distances=similarity[movie_index]
    movies_list=sorted(list(enumerate(distances)),reverse=True,key=lambda x:x[1])[1:6] #finding the 5 most similar movies
    for i in movies_list:
        print(new_df.iloc[i[0]].title)

In [314]:
recommend('Spider-Man')

Spider-Man 3
Spider-Man 2
The Amazing Spider-Man 2
Arachnophobia
Kick-Ass

In [315]:
pickle.dump(new_df.to_dict(),open('movies.pkl','wb'))

In [316]:
import pickle

In [317]:
pickle.dump(similarity,open('similarity.pkl','wb'))

In [318]:
new_df

,id,title,tags,overview,genres,cast,crew,overview1
0,19995,Avatar,"in the 22nd century, a parapleg marin is dispa...","[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believ to be dead, ha c...","[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski],"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,a cryptic messag from bondâ€™ past send him on a...,"[A, cryptic, message, from, Bondâ€™s, past, send...","[Action, Adventure, Crime]","[DanielCraig, ChristophWaltz, LÃ©aSeydoux]",[SamMendes],A cryptic message from Bondâ€™s past sends him o...
3,49026,The Dark Knight Rises,follow the death of district attorney harvey d...,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan],Following the death of District Attorney Harve...
4,49529,John Carter,"john carter is a war-weary, former militari ca...","[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton],"John Carter is a war-weary, former military ca..."
...,...,...,...,...,...,...,...,...
4803,9367,El Mariachi,el mariachi just want to play hi guitar and ca...,"[El, Mariachi, just, wants, to, play, his, gui...","[Action, Crime, Thriller]","[CarlosGallardo, JaimedeHoyos, PeterMarquardt]",[RobertRodriguez],El Mariachi just wants to play his guitar and ...
4804,72766,Newlyweds,a newlyw couple' honeymoon is upend by the arr...,"[A, newlywed, couple's, honeymoon, is, upended...","[Comedy, Romance]","[EdwardBurns, KerryBishÃ©, MarshaDietlein]",[EdwardBurns],A newlywed couple's honeymoon is upended by th...
4805,231617,"Signed, Sealed, Delivered","""signed, sealed, delivered"" introduc a dedic q...","[""Signed,, Sealed,, Delivered"", introduces, a,...","[Comedy, Drama, Romance, TVMovie]","[EricMabius, KristinBooth, CrystalLowe]",[ScottSmith],"""Signed, Sealed, Delivered"" introduces a dedic..."
4806,126186,Shanghai Calling,when ambiti new york attorney sam is sent to s...,"[When, ambitious, New, York, attorney, Sam, is...",[],"[DanielHenney, ElizaCoupe, BillPaxton]",[DanielHsia],When ambitious New York attorney Sam is sent t...
4807,25975,My Date with Drew,ever sinc the second grade when he first saw h...,"[Ever, since, the, second, grade, when, he, fi...",[Documentary],"[DrewBarrymore, BrianHerzlinger, CoreyFeldman]",[BrianHerzlinger],Ever since the second grade when he first saw ...

In [319]:
new_df['cast']=listToString('cast')

C:\Users\91906\AppData\Local\Temp\ipykernel_14376\4078227022.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['cast']=listToString('cast')

In [320]:
def convert(obj):
    str1 = ""
    for i in ast.literal_eval(obj):
        for i in ast.literal_eval(obj):   
            str1 += i
    return str1

In [321]:
new_df

,id,title,tags,overview,genres,cast,crew,overview1
0,19995,Avatar,"in the 22nd century, a parapleg marin is dispa...","[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]",cast,[JamesCameron],"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believ to be dead, ha c...","[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]",cast,[GoreVerbinski],"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,a cryptic messag from bondâ€™ past send him on a...,"[A, cryptic, message, from, Bondâ€™s, past, send...","[Action, Adventure, Crime]",cast,[SamMendes],A cryptic message from Bondâ€™s past sends him o...
3,49026,The Dark Knight Rises,follow the death of district attorney harvey d...,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]",cast,[ChristopherNolan],Following the death of District Attorney Harve...
4,49529,John Carter,"john carter is a war-weary, former militari ca...","[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]",cast,[AndrewStanton],"John Carter is a war-weary, former military ca..."
...,...,...,...,...,...,...,...,...
4803,9367,El Mariachi,el mariachi just want to play hi guitar and ca...,"[El, Mariachi, just, wants, to, play, his, gui...","[Action, Crime, Thriller]",cast,[RobertRodriguez],El Mariachi just wants to play his guitar and ...
4804,72766,Newlyweds,a newlyw couple' honeymoon is upend by the arr...,"[A, newlywed, couple's, honeymoon, is, upended...","[Comedy, Romance]",cast,[EdwardBurns],A newlywed couple's honeymoon is upended by th...
4805,231617,"Signed, Sealed, Delivered","""signed, sealed, delivered"" introduc a dedic q...","[""Signed,, Sealed,, Delivered"", introduces, a,...","[Comedy, Drama, Romance, TVMovie]",cast,[ScottSmith],"""Signed, Sealed, Delivered"" introduces a dedic..."
4806,126186,Shanghai Calling,when ambiti new york attorney sam is sent to s...,"[When, ambitious, New, York, attorney, Sam, is...",[],cast,[DanielHsia],When ambitious New York attorney Sam is sent t...
4807,25975,My Date with Drew,ever sinc the second grade when he first saw h...,"[Ever, since, the, second, grade, when, he, fi...",[Documentary],cast,[BrianHerzlinger],Ever since the second grade when he first saw ...

In [252]:
new_df['overview']=new_df['overview'].apply(convert)

ValueError: malformed node or string: ['In', 'the', '22nd', 'century,', 'a', 'paraplegic', 'Marine', 'is', 'dispatched', 'to', 'the', 'moon', 'Pandora', 'on', 'a', 'unique', 'mission,', 'but', 'becomes', 'torn', 'between', 'following', 'orders', 'and', 'protecting', 'an', 'alien', 'civilization.']

In [ ]:
new_df["overview"][0]